services:
  postgres:
    container_name: next-todo
    environment:
      - POSTGRES_DB=todos
      - POSTGRES_PASSWORD=todos1234
      - POSTGRES_USER=postgres
    ports:
      - 5600:5432
    image: postgres:16.3-alpine
